### ISSUE TITLE
Color Pallete of Neofusion for a new port

### ISSUE THREAD

**Issue by LyiarCodie** [diegoulloao/neofusion.nvim#11]
Hello, can you share the color pallete of this theme? I wanted to create a version for **Visual Studio** 🙏💙❤

**Comment by diegoulloao** [comment]
> Hello, can you share the color pallete of this theme? I wanted to create a version for **Visual Studio** 🙏💙❤

Sure, here it is!

**Comment by diegoulloao** [comment]
> Hello, can you share the color pallete of this theme? I wanted to create a version for **Visual Studio** 🙏💙❤

Sure, here it is! https://github.com/diegoulloao/neofusion.nvim/blob/main/lua/neofusion/palette.lua

**Comment by diegoulloao** [comment]
Btw there's a Visual Studio Code port you could check if helps 🙂

**Comment by LyiarCodie** [comment]
Yeeah, i tried to use a theme converter to port your vscode theme to Visual studio, but some parts of the IDE was visually broken like the Nuget Package Console, some inputs and checkboxes 😅

**Comment by diegoulloao** [comment]
Yes, probably you'll need to do some manual work there. I've also tried porting a tmTheme to json without complete success.
Lmk if you build something, I can link the theme to the ports section on all Neofusion readme's 🙂

Good luck! ✨
