### ISSUE TITLE
[Feature]: Windows Terminal Theme?

### ISSUE THREAD

**Issue by JustBarnt** [diegoulloao/neofusion.nvim#8]
Was just curious if you have any plans to add a windows terminal theme? I love this in neovim and I would thoroughly enjoy my terminal matching!

**Comment by diegoulloao** [comment]
@JustBarnt could you test this one? https://github.com/diegoulloao/neofusion.winterm

**Comment by diegoulloao** [comment]
> @diegoulloao Looks good to me! Thanks!

You're welcome. Enjoy!
