### ISSUE TITLE
[Feature]: Wezterm version

### ISSUE THREAD

**Issue by serhez** [diegoulloao/neofusion.nvim#9]
Could we have a Wezterm port? Thanks! :)

**Comment by diegoulloao** [comment]
@serhez actually is on the list 👍🏻 coming in the next days

**Comment by serhez** [comment]
Thanks!

**Comment by diegoulloao** [comment]
You're welcome!

**Comment by diegoulloao** [comment]
@serhez https://github.com/diegoulloao/neofusion.wezterm/
